name: foody
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_stars: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/